.PHONY: clean All

All:
	@echo "----------Building project:[ manysteps-lib - Release ]----------"
	@"$(MAKE)" -f  "manysteps-lib.mk"
clean:
	@echo "----------Cleaning project:[ manysteps-lib - Release ]----------"
	@"$(MAKE)" -f  "manysteps-lib.mk" clean
