.PHONY: clean All

All:
	@echo "----------Building project:[ manysteps-unb-gr - Release ]----------"
	@"$(MAKE)" -f  "manysteps-unb-gr.mk"
clean:
	@echo "----------Cleaning project:[ manysteps-unb-gr - Release ]----------"
	@"$(MAKE)" -f  "manysteps-unb-gr.mk" clean
