.PHONY: clean All

All:
	@echo "----------Building project:[ manysteps-unb - Release ]----------"
	@"$(MAKE)" -f  "manysteps-unb.mk"
clean:
	@echo "----------Cleaning project:[ manysteps-unb - Release ]----------"
	@"$(MAKE)" -f  "manysteps-unb.mk" clean
